version: '3'

services:
  web:
    networks:
      - bbc_networks
    container_name: bbc-app
    image: userhubdocker1/bbc:latest
    ports:
      - "1234:1234"
    depends_on:
#      - db
      - redis-db
    environment:
      - DJANGO_DEBUG=False
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  redis-db:
    container_name: bbc-redis
    image: redis
    ports:
      - "6380:6379"
    networks:
      - bbc_networks
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: postgres_bbc
    environment:
      POSTGRES_DB: bbc_db
      POSTGRES_USER: bbc_user
      POSTGRES_PASSWORD: bbc_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bbc_networks
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bbc_networks:
    driver: bridge
